# Generated by Django 5.1.2 on 2024-11-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_pedido_productopedido_pedido_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
