# Generated by Django 5.1.3 on 2024-11-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
