# Generated by Django 5.1.3 on 2024-11-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articulo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
