# Generated by Django 5.1.3 on 2024-11-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_producto_remove_articulo_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
