# Generated by Django 5.1.3 on 2024-11-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_articulo_stock_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='contenido',
        ),
    ]
