# Generated by Django 5.1.3 on 2024-11-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_articulo_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
