# Generated by Django 5.1.2 on 2024-11-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_articulo_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
