# Generated by Django 5.1.2 on 2024-11-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_articulo_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='is_deleted',
        ),
    ]
